### ISSUE TITLE
BasedOnStyle setting causes error message

### ISSUE THREAD

**Issue by anntzer** [johnmcfarlane/unformat#7]
A BasedOnStyle entry in .clang-format leads to the message
```
Unrecognized setting, 'BasedOnStyle:Chromium', in .clang-format configuration.
```

**Comment by johnmcfarlane** [comment]
Can I ask what version of clang-format you're using?

**Comment by anntzer** [comment]
4.0.1 from Arch Linux repository.

**Comment by johnmcfarlane** [comment]
Problem was that when you run `clang-format -dump-config` it produces a config file with `BasedOnStyle` commented out so I never thought to add it. Should be fixed now. Thanks.
